services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: train-api-db
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    env_file:
      - .env
    volumes:
      - ./pgdb:/var/lib/postgresql/data

volumes:
  pgdb: